import { fetchBySearch, fetchDetailedBeer } from '@/api/api';
import { BASE_ITEM_PER_PAGE, BASE_PAGE } from '@/components/constants';
import DetailedBeerItem, { DetailedBeerData } from '@/components/detailed-beer-item';
import Footer from '@/components/footer';
import PaginationSection from '@/components/pagination-section';
import ResultsSection, { Beer } from '@/components/result-section';
import SearchSection from '@/components/search-section';
import styles from '@/styles/Home.module.css';
import { GetServerSideProps } from 'next';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import { ParsedUrlQuery } from 'querystring';
const inter = Inter({ subsets: ['latin'] });

interface Props {
  fetchedBeers: Beer[];
  detailedBeer: DetailedBeerData | null;
}

interface Query extends ParsedUrlQuery {
  page?: string;
  per_page?: string;
  search?: string;
  details?: string;
}

export const getServerSideProps: GetServerSideProps<Props, Query> = async ({ query }) => {
  const page = typeof query.page === 'string' ? query.page : BASE_PAGE.toString();
  const itemPerPage = typeof query.per_page === 'string' ? query.per_page : BASE_ITEM_PER_PAGE;
  const search = Array.isArray(query.search) ? query.search.join('_') : query.search || '';
  const detailedBeerID = query.details ? parseInt(query.details as string, 10) : null;

  try {
    const [fetchedBeers, detailedBeer] = await Promise.all([
      fetchBySearch(search, page, itemPerPage),
      detailedBeerID ? fetchDetailedBeer(detailedBeerID) : fetchDetailedBeer(),
    ]);

    return {
      props: { fetchedBeers, detailedBeer },
    };
  } catch (error) {
    console.error(error);

    return {
      props: { fetchedBeers: [], detailedBeer: null },
    };
  }
};

export default function Home({ fetchedBeers, detailedBeer }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
        ></link>
      </Head>
      <div className={styles.container}>
        <header className={styles.header}>
          <h1 style={{ textDecoration: 'none' }}>Beer academy</h1>
        </header>
        <main className={styles.main}>
          <h2>Beer catalogue</h2>

          <p>
            The Beer Academy is a renowned institution for beer enthusiasts, offering educational
            programs, workshops, and tastings to explore the art and science of brewing beer. Cheers
            to beer education!
          </p>

          <SearchSection />

          <PaginationSection />
          <div
            className={styles['beer-section']}
            style={{ gridTemplateColumns: detailedBeer ? '1fr 1fr ' : '1fr' }}
          >
            <ResultsSection fetchedBeers={fetchedBeers} />
            {detailedBeer && (
              <div className="beer-info">
                <DetailedBeerItem detailedBeer={detailedBeer} />
              </div>
            )}
          </div>
        </main>
        <Footer />
      </div>
    </>
  );
}
