import { fetchBySearch, fetchDetailedBeer } from '@/api/api';
import { BASE_ITEM_PER_PAGE, BASE_PAGE } from '@/components/constants';
import DetailedBeerItem, { DetailedBeerData } from '@/components/detailed-beer-item';
import RootLayout from '@/components/layout';
import PaginationSection from '@/components/pagination-section';
import ResultsSection, { Beer } from '@/components/result-section';
import styles from '@/styles/Home.module.css';
import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { ParsedUrlQuery } from 'querystring';
import { NextPageWithLayout } from './_app';
// const inter = Inter({ subsets: ['latin'] });

interface HomeGSSProps {
  fetchedBeers: Beer[];
  detailedBeer: DetailedBeerData | null;
}

export interface Query extends ParsedUrlQuery {
  page?: string;
  per_page?: string;
  search?: string;
  details?: string;
}

export const getServerSideProps: GetServerSideProps<HomeGSSProps, Query> = async ({ query }) => {
  const page = typeof query.page === 'string' ? query.page : BASE_PAGE.toString();
  const itemPerPage = typeof query.per_page === 'string' ? query.per_page : BASE_ITEM_PER_PAGE;
  const search = Array.isArray(query.search) ? query.search.join('_') : query.search || '';
  const detailedBeerID = query.details ? +(query.details as string) : null;

  try {
    const [fetchedBeers, detailedBeer] = await Promise.all([
      fetchBySearch(search, page, itemPerPage),
      detailedBeerID ? fetchDetailedBeer(detailedBeerID) : fetchDetailedBeer(),
    ]);

    return {
      props: { fetchedBeers, detailedBeer },
    };
  } catch (error) {
    console.error(error);

    return {
      props: { fetchedBeers: [], detailedBeer: null },
    };
  }
};

const Home: NextPageWithLayout<HomeGSSProps> = ({ fetchedBeers, detailedBeer }) => {
  const router = useRouter();
  const perPage = Number(router.query.per_page) || +BASE_ITEM_PER_PAGE;
  const isNextPageDisabled = fetchedBeers.length < perPage;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
        ></link>
      </Head>
      <PaginationSection isNextPageDisabled={isNextPageDisabled} />
      <div
        className={styles['beer-section']}
        data-testid="beer-section"
        style={{ gridTemplateColumns: detailedBeer ? '1fr 1fr ' : '1fr' }}
      >
        <ResultsSection fetchedBeers={fetchedBeers} />
        {detailedBeer && (
          <div className="beer-info">
            <DetailedBeerItem detailedBeer={detailedBeer} />
          </div>
        )}
      </div>
    </>
  );
};

Home.getLayout = (page) => {
  return <RootLayout>{page}</RootLayout>;
};

export default Home;
